# site title
title: Shaoyao·琚

# user name or organization name
user: juzhiyuan

# issue repository
repository: https://github.com/juzhiyuan/Segment

# multi-author
authors:

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: 7#ab78331e31f6646eb118390566ac3ab5c31cec9

# posts per page
perpage: 8


# advance config

# organization repository (?)
organization: false

# post order
# order by create time" or "update time"
# 'UPDATED_AT' or 'CREATED_AT'
order: 'UPDATED_AT'
